sudo: false
language: elixir
elixir:
  - 1.2.3
otp_release:
  - 18.2
script:
  - mix test
after_script:
  - MIX_ENV=test mix coveralls.travis
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
notifications:
  email:
    recipients:
      - m.t.williams@live.com
    on_success: change
    on_failure: change
